### ISSUE TITLE
NAT什么时候修

### ISSUE THREAD

**Issue by lkcdm** [runyutech/mofang-rcs#5]
已经处理了

**Comment by tcomil** [comment]
![IMG_4292](https://github.com/user-attachments/assets/8e3edce1-e14c-4bea-a69d-4b3c86733f9d)

**Comment by tcomil** [comment]
制造cdn的另一个广州小孩(陈康龙)雨云用户势力 与卢意叛军串通一气🌝遭报应了 之前辱骂军方 呵呵🌝它的猫下地狱了(我不确定猫是否能下地狱)🌝🌝🌝 非要搞博客网站 有什么用啊🌝它没有@premium 还在博客中弄个假的@premium 标志 就是没本事🌝

**Comment by tcomil** [comment]
https://x.com/bukaixyz/status/1830248926068511021?s=61

**Comment by tcomil** [comment]
神其实一直在默默帮助军方 之前卢意叛军大疆无人机摔了🌝(虽然又免费换了个新的) 欧阳云睿BTRFS文件系统故障,现在雨云用户势力的猫下地狱了🌝就是遭报应了🌝

『亲爱的弟兄，不要自己申冤，宁可让步，听凭主怒；因为经上记着：“主说：申冤在我，我必报应。”』罗马书 12:19
